### ISSUE TITLE
[Component] Formfield

### ISSUE THREAD

**Issue by aycil-alican** [adevinta/spark-ios#782] opened 2024-01-29 13:10 UTC
```[tasklist]
### Tasks
```

**Comment by turolopezsanabria** [comment] 2024-03-12 10:55
Hey @aycil-alican 
We've just made an adjustment on the colour of the * required star:

As reported [here](https://adevinta.slack.com/archives/C056PNNGWTY/p1709312447255489) the * is not visible enough.

Solution

Adjust the colour
❌ current: onSurface / Dim 3


![Image](https://github.com/adevinta/spark-ios/assets/23620759/8cd03c1b-1177-45f8-b32e-9c3efce770e2)


✅ desired: onSurface / Dim 1



![Image](https://github.com/adevinta/spark-ios/assets/23620759/789b414f-3345-4390-9d27-7fe13f82fd80)

**Comment by aycil-alican** [comment] 2024-03-12 12:47
@turolopezsanabria Do we have a final decision on title font? There was a issue on Figma.

**Comment by thomas-leguellec** [comment] 2024-03-13 09:16
Answer: Body 2

**Comment by aycil-alican** [comment] 2024-03-13 16:40
There wasn't disable/enable attribute for checkbox group component. Consumer was disabling checkboxes one by one in group component. I also added isEnabled parameter to checkbox group uikit component to disable and enable all checkboxes at same time with this task.

**Comment by aycil-alican** [comment] 2024-04-11 07:38
to test: component/formfield_782, Formfield UIkit side was developed according to Figa File. There is a disable issue for checkbox group. It isnt releated with Formfield. I fixed this issue with different task. (https://github.com/orgs/adevinta/projects/4/views/19?pane=issue&itemId=57535532#:~:text=group%20disable%20issue-,%23864,-Edit)

**Comment by elisa-hery** [comment] 2024-04-30 15:30
Hey @aycil-alican , based on the [checklist](https://docs.google.com/spreadsheets/d/1DBGCysLrFFcoFXKYpMmQF-Anmt9Qqlc8_kXEzwOLNB4/edit#gid=925235290&range=1:14), here are my remarks : 
1. checkbox group does not work (I'm not able to check / uncheck) --> fixed in [this ticket](https://github.com/orgs/adevinta/projects/4/views/19?pane=issue&itemId=57535532)
2. unwanted space in front of horizontal radio button group --> handled in [this ticket](https://github.com/orgs/adevinta/projects/4/views/19?pane=issue&itemId=61325069)

Remains the design testing session !

**Comment by elisa-hery** [comment] 2024-05-06 08:25
@aycil-alican quick summary about Formfield UI kit : 
- all bugs listed in the [testing gsheet](https://docs.google.com/spreadsheets/d/1DBGCysLrFFcoFXKYpMmQF-Anmt9Qqlc8_kXEzwOLNB4/edit#gid=925235290&range=7:15) are fixed ✅ 
- there is a weird behavior on radio button UI kit (see video below) but you told me this is not a bug : there is no scrollview on the radio button default so when items are not fit the screen we cant see them properly. 

https://github.com/adevinta/spark-ios/assets/142396647/1eec9aa5-05ea-4ccd-b19e-08d0d4eaf44c


@adevinta/spark-design --> Formfield UI kit is ready for design review !

**Comment by ChrisDesignOps** [comment] 2024-05-07 15:44
Holo @aycil-alican, when Title is an `Attribute Text` the Mandatory * change the line-height of the Title (maybe is something irrelevant if this attribute is just an example. It would also be nice not display an Error text on the example)

https://github.com/adevinta/spark-ios/assets/81374770/afe6d2df-04f5-4928-a496-c1b9191d765b

**Comment by ChrisDesignOps** [comment] 2024-05-07 15:56
✅ Done the review from Design.

I only saw things on the demo that can be improved (but aren't related to the component):

1. Selecting component `Basic` and `Fill screen`, the demo breaks.
2. Selecting `Horizontal radio or checks` and changing props the label of the second item breaks.
3. `Single Radio Button` it’s something not possible to do on a form.

**Comment by aycil-alican** [comment] 2024-05-08 10:56
@ChrisDesignOps Thanks for the review;

**Comment by ChrisDesignOps** [comment] 2024-05-13 14:23
Holo @aycil-alican sorry for my delayed answer. 
Them from design it's ok to publish the component. Thx!

**Closed** 2024-05-21 11:15 UTC
Labels: UIKit, Component, Design review
